version: '3'

services:
 maria:
  image: "mariadb:10.3-bionic"
  restart: always
  environment:
   MYSQL_ROOT_PASSWORD: ddtr 

 api:
  build: ./ddtr
  restart: always
  volumes:
   - ./ddtr:/apps/home
  ports:
   - 8081:8080

