version: '3'

services:
 maria:
  image: "mariadb:10.3-bionic"
  restart: always
  environment:
   MYSQL_ROOT_PASSWORD: ddtr 

 api:
  build: ./server
  restart: always
  volumes:
   - ./server/src:/apps/home
  ports:
   - 8081:8080
   - 5051:5005
 adminer:
  image: adminer
  restart: always
  ports:
    - 80:8080
